2018-06-02 09:27:40,536 [Dummy-1:7144] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 09:27:57,345 [Thread-2:7800] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 124556
2018-06-02 09:27:57,676 [Thread-3:11280] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "F:\env\env_mysite\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLPattern '^$' [name='index']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2018-06-02 09:27:57,712 [Thread-3:11280] [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2094
2018-06-02 09:30:04,974 [Thread-4:9560] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 124691
2018-06-02 09:30:45,710 [Thread-8:19164] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 86
2018-06-02 09:31:27,058 [Thread-11:17720] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 126095
2018-06-02 09:31:42,675 [Thread-14:10288] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 137425
2018-06-02 09:31:45,144 [Thread-15:11304] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 137424
2018-06-02 09:34:01,142 [Thread-16:5412] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "F:\env\env_mysite\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLPattern '^$' [name='index']>]], 'path': 'index'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2018-06-02 09:34:01,156 [Thread-16:5412] [django.server:124] [basehttp:log_message] [WARNING]- "GET /index HTTP/1.1" 404 2076
2018-06-02 09:34:28,093 [Thread-17:16312] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 125960
2018-06-02 09:51:14,332 [Dummy-1:11032] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 09:51:17,427 [Thread-2:13152] [django.server:124] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 94401
2018-06-02 09:52:01,261 [Dummy-1:17116] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 09:52:01,401 [Thread-2:12800] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06442270>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06442030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x064568D0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204FF0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:01,512 [Thread-2:12800] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 87
2018-06-02 09:52:28,770 [Thread-5:15212] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x064788A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x061C4588>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204430>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204030>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:28,776 [Thread-5:15212] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x064788A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x061C4588>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204430>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204030>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:28,779 [Thread-5:15212] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 87
2018-06-02 09:52:30,639 [Thread-6:7404] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06478858>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06478978>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204710>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:30,644 [Thread-6:7404] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06478858>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06478978>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204710>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:30,647 [Thread-6:7404] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 87
2018-06-02 09:52:33,369 [Thread-7:18508] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06478858>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x061C4588>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204A10>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204650>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:33,371 [Thread-7:18508] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06478858>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x061C4588>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06204A10>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06204650>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:52:33,378 [Thread-7:18508] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 87
2018-06-02 09:54:20,499 [Thread-9:2976] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x064789C0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06478930>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06448F50>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x062047B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:54:20,505 [Thread-9:2976] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x064789C0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06478930>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06448F50>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x062047B0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:54:20,514 [Thread-9:2976] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 109
2018-06-02 09:54:58,916 [Dummy-1:11208] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 09:55:18,350 [Dummy-1:15048] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 09:56:40,285 [Thread-2:9968] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069BD2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x069BD030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x069CAF50>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069B3530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:56:40,288 [Thread-2:9968] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069BD2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x069BD030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x069CAF50>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069B3530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:56:40,291 [Thread-2:9968] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 09:58:03,111 [Thread-4:11820] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069BD2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C04300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D5D0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069CA890>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,116 [Thread-4:11820] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069BD2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C04300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D5D0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069CA890>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,125 [Thread-4:11820] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 09:58:03,621 [Thread-5:17336] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C238A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x069BD2B8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D890>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06C0D530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,625 [Thread-5:17336] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C238A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x069BD2B8>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D890>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06C0D530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,628 [Thread-5:17336] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 09:58:03,818 [Thread-6:13644] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C238A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C04300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D870>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069CA810>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,824 [Thread-6:13644] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C238A0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C04300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0D870>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x069CA810>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:03,826 [Thread-6:13644] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 09:58:04,007 [Thread-7:9824] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C239C0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C23930>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0DB30>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06C0D710>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:04,011 [Thread-7:9824] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06C239C0>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06C23930>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06C0DB30>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06C0D710>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 09:58:04,015 [Thread-7:9824] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 10:02:38,909 [Dummy-1:10756] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 10:02:38,994 [Thread-2:7104] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06A8F2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06A8F030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06F04B90>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06A85FF0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': 'aaaaa', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:02:38,997 [Thread-2:7104] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06A8F2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06A8F030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06F04B90>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06A85FF0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': 'aaaaa', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:02:38,999 [Thread-2:7104] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 10:02:42,623 [Thread-3:16648] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06A8F2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06F09300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06A85590>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06A851F0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': 'aaaaa', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:02:42,627 [Thread-3:16648] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06A8F2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x06F09300>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06A85590>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06A851F0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': 'aaaaa', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:02:42,632 [Thread-3:16648] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 10:06:21,242 [Dummy-1:14000] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 10:06:32,993 [Dummy-1:7348] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 10:06:40,122 [Thread-2:17608] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x05E7C2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x05E7C030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x05E8AF30>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x05E72530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:06:40,127 [Thread-2:17608] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'SITE_NAME' in template 'index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'SITE_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [SITE_NAME] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x05E7C2B8>>, 'request': <WSGIRequest: GET '/'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x05E7C030>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x05E8AF30>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x05E72530>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME ': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'request': <WSGIRequest: GET '/'>}]
2018-06-02 10:06:40,132 [Thread-2:17608] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 118
2018-06-02 10:07:49,488 [Dummy-1:17588] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 10:10:45,388 [Dummy-1:7512] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2018-06-02 10:10:46,654 [Thread-2:18988] [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 166
2018-06-02 15:20:15,067 [MainThread:8264] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-02 15:20:15,068 [MainThread:8264] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:20:15,069 [MainThread:8264] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-06-02 15:21:38,235 [MainThread:3336] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-02 15:21:38,236 [MainThread:3336] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:21:38,238 [MainThread:3336] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-02 15:21:38,312 [MainThread:3336] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:21:38,314 [MainThread:3336] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2018-06-02 15:27:39,327 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-02 15:27:39,327 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:27:39,329 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@sql_mode; args=None
2018-06-02 15:27:39,342 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-02 15:27:39,425 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2018-06-02 15:27:39,426 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2018-06-02 15:27:39,432 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2018-06-02 15:27:39,432 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime(6) NOT NULL); (params None)
2018-06-02 15:27:39,582 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.149) CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime(6) NOT NULL); args=None
2018-06-02 15:27:39,641 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.058) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=['django_migrations']
2018-06-02 15:27:39,646 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=['django_migrations']
2018-06-02 15:27:39,650 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=['django_migrations']
2018-06-02 15:27:39,653 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'; args=['django_migrations']
2018-06-02 15:27:39,658 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
2018-06-02 15:27:39,845 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.186) CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); args=None
2018-06-02 15:27:39,851 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=['django_content_type']
2018-06-02 15:27:39,856 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=['django_content_type']
2018-06-02 15:27:39,865 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=['django_content_type']
2018-06-02 15:27:39,871 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'django_content_type'; args=['django_content_type']
2018-06-02 15:27:39,878 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (`app_label`, `model`); (params ())
2018-06-02 15:27:39,996 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.116) ALTER TABLE `django_content_type` ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (`app_label`, `model`); args=()
2018-06-02 15:27:39,998 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SHOW FULL TABLES; args=None
2018-06-02 15:27:40,012 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0001_initial', '2018-06-02 07:27:39.999304'); args=['contenttypes', '0001_initial', '2018-06-02 07:27:39.999304']
2018-06-02 15:27:40,033 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
2018-06-02 15:27:40,635 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.602) ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; args=[]
2018-06-02 15:27:40,640 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `django_content_type` DROP COLUMN `name`; (params ())
2018-06-02 15:27:40,886 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.246) ALTER TABLE `django_content_type` DROP COLUMN `name`; args=()
2018-06-02 15:27:40,890 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:27:40,893 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0002_remove_content_type_name', '2018-06-02 07:27:40.891720'); args=['contenttypes', '0002_remove_content_type_name', '2018-06-02 07:27:40.891720']
2018-06-02 15:27:40,931 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); (params None)
2018-06-02 15:27:41,066 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.135) CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL); args=None
2018-06-02 15:27:41,069 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=['auth_permission']
2018-06-02 15:27:41,072 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=['auth_permission']
2018-06-02 15:27:41,074 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=['auth_permission']
2018-06-02 15:27:41,076 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_permission'; args=['auth_permission']
2018-06-02 15:27:41,082 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
2018-06-02 15:27:41,288 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.205) CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); args=None
2018-06-02 15:27:41,295 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.007) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group'; args=['auth_group']
2018-06-02 15:27:41,301 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group'; args=['auth_group']
2018-06-02 15:27:41,304 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2018-06-02 15:27:41,430 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.123) CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2018-06-02 15:27:41,436 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group_permissions'; args=['auth_group_permissions']
2018-06-02 15:27:41,442 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group_permissions'; args=['auth_group_permissions']
2018-06-02 15:27:41,448 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'auth_group_permissions'; args=['auth_group_permissions']
2018-06-02 15:27:41,467 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params ())
2018-06-02 15:27:41,783 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.314) ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=()
2018-06-02 15:27:41,784 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (`content_type_id`, `codename`); (params ())
2018-06-02 15:27:41,964 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.176) ALTER TABLE `auth_permission` ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (`content_type_id`, `codename`); args=()
2018-06-02 15:27:41,966 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params ())
2018-06-02 15:27:42,357 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.387) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=()
2018-06-02 15:27:42,358 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params ())
2018-06-02 15:27:42,733 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.374) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=()
2018-06-02 15:27:42,733 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_group_permissions` ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (`group_id`, `permission_id`); (params ())
2018-06-02 15:27:42,912 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.178) ALTER TABLE `auth_group_permissions` ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (`group_id`, `permission_id`); args=()
2018-06-02 15:27:42,914 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2018-06-02 15:27:42,916 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0001_initial', '2018-06-02 07:27:42.915420'); args=['auth', '0001_initial', '2018-06-02 07:27:42.915420']
2018-06-02 15:27:42,944 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
2018-06-02 15:27:43,309 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.364) ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; args=[]
2018-06-02 15:27:43,311 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,313 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0002_alter_permission_name_max_length', '2018-06-02 07:27:43.312233'); args=['auth', '0002_alter_permission_name_max_length', '2018-06-02 07:27:43.312233']
2018-06-02 15:27:43,332 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,333 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0003_alter_user_email_max_length', '2018-06-02 07:27:43.332841'); args=['auth', '0003_alter_user_email_max_length', '2018-06-02 07:27:43.332841']
2018-06-02 15:27:43,378 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,388 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.008) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0004_alter_user_username_opts', '2018-06-02 07:27:43.379934'); args=['auth', '0004_alter_user_username_opts', '2018-06-02 07:27:43.379934']
2018-06-02 15:27:43,423 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,424 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0005_alter_user_last_login_null', '2018-06-02 07:27:43.423579'); args=['auth', '0005_alter_user_last_login_null', '2018-06-02 07:27:43.423579']
2018-06-02 15:27:43,450 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,454 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0006_require_contenttypes_0002', '2018-06-02 07:27:43.451692'); args=['auth', '0006_require_contenttypes_0002', '2018-06-02 07:27:43.451692']
2018-06-02 15:27:43,496 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,499 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0007_alter_validators_add_error_messages', '2018-06-02 07:27:43.497648'); args=['auth', '0007_alter_validators_add_error_messages', '2018-06-02 07:27:43.497648']
2018-06-02 15:27:43,531 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,532 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0008_alter_user_username_max_length', '2018-06-02 07:27:43.531737'); args=['auth', '0008_alter_user_username_max_length', '2018-06-02 07:27:43.531737']
2018-06-02 15:27:43,558 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SHOW FULL TABLES; args=None
2018-06-02 15:27:43,559 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0009_alter_user_last_name_max_length', '2018-06-02 07:27:43.558810'); args=['auth', '0009_alter_user_last_name_max_length', '2018-06-02 07:27:43.558810']
2018-06-02 15:27:43,585 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NULL, `is_superuser` bool NOT NULL, `username` varchar(150) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(150) NOT NULL, `email` varchar(254) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL, `avatar` varchar(200) NULL, `qq` varchar(20) NULL, `mobile` varchar(11) NULL UNIQUE, `url` varchar(100) NULL); (params None)
2018-06-02 15:27:43,793 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.207) CREATE TABLE `blog_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NULL, `is_superuser` bool NOT NULL, `username` varchar(150) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(150) NOT NULL, `email` varchar(254) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL, `avatar` varchar(200) NULL, `qq` varchar(20) NULL, `mobile` varchar(11) NULL UNIQUE, `url` varchar(100) NULL); args=None
2018-06-02 15:27:43,814 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.021) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,816 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,819 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,824 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,826 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,828 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,831 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,832 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,834 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,839 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,842 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,844 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,846 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,848 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,851 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user'; args=['blog_user']
2018-06-02 15:27:43,852 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); (params None)
2018-06-02 15:27:44,154 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.301) CREATE TABLE `blog_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL); args=None
2018-06-02 15:27:44,156 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_groups'; args=['blog_user_groups']
2018-06-02 15:27:44,158 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_groups'; args=['blog_user_groups']
2018-06-02 15:27:44,160 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_groups'; args=['blog_user_groups']
2018-06-02 15:27:44,161 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); (params None)
2018-06-02 15:27:44,296 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.134) CREATE TABLE `blog_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL); args=None
2018-06-02 15:27:44,302 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_user_permissions'; args=['blog_user_user_permissions']
2018-06-02 15:27:44,310 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_user_permissions'; args=['blog_user_user_permissions']
2018-06-02 15:27:44,319 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_user_user_permissions'; args=['blog_user_user_permissions']
2018-06-02 15:27:44,327 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_ad` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `description` varchar(200) NOT NULL, `image_url` varchar(100) NOT NULL, `callback_url` varchar(200) NULL, `date_publish` datetime(6) NOT NULL, `index` integer NOT NULL); (params None)
2018-06-02 15:27:44,471 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.143) CREATE TABLE `blog_ad` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `description` varchar(200) NOT NULL, `image_url` varchar(100) NOT NULL, `callback_url` varchar(200) NULL, `date_publish` datetime(6) NOT NULL, `index` integer NOT NULL); args=None
2018-06-02 15:27:44,477 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,480 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,483 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,487 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,490 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,493 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,495 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_ad'; args=['blog_ad']
2018-06-02 15:27:44,497 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_article` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `desc` varchar(50) NOT NULL, `content` longtext NOT NULL, `click_count` integer NOT NULL, `is_recommend` bool NOT NULL, `date_publish` datetime(6) NOT NULL); (params None)
2018-06-02 15:27:44,646 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.148) CREATE TABLE `blog_article` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `desc` varchar(50) NOT NULL, `content` longtext NOT NULL, `click_count` integer NOT NULL, `is_recommend` bool NOT NULL, `date_publish` datetime(6) NOT NULL); args=None
2018-06-02 15:27:44,648 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,650 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,653 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,658 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,660 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,663 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,665 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:44,666 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_category` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(30) NOT NULL, `index` integer NOT NULL); (params None)
2018-06-02 15:27:45,157 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.489) CREATE TABLE `blog_category` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(30) NOT NULL, `index` integer NOT NULL); args=None
2018-06-02 15:27:45,162 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_category'; args=['blog_category']
2018-06-02 15:27:45,183 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_category'; args=['blog_category']
2018-06-02 15:27:45,186 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_category'; args=['blog_category']
2018-06-02 15:27:45,200 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_comment` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `content` longtext NOT NULL, `username` varchar(30) NULL, `email` varchar(50) NULL, `url` varchar(100) NULL, `date_publish` datetime(6) NOT NULL, `article_id` integer NULL, `pid_id` integer NULL, `user_id` integer NULL); (params None)
2018-06-02 15:27:45,342 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.140) CREATE TABLE `blog_comment` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `content` longtext NOT NULL, `username` varchar(30) NULL, `email` varchar(50) NULL, `url` varchar(100) NULL, `date_publish` datetime(6) NOT NULL, `article_id` integer NULL, `pid_id` integer NULL, `user_id` integer NULL); args=None
2018-06-02 15:27:45,344 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,346 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,349 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,351 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,352 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,357 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,360 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,361 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,363 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_comment'; args=['blog_comment']
2018-06-02 15:27:45,366 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_links` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `description` varchar(200) NOT NULL, `callback_url` varchar(200) NOT NULL, `date_publish` datetime(6) NOT NULL, `index` integer NOT NULL); (params None)
2018-06-02 15:27:45,511 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.145) CREATE TABLE `blog_links` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(50) NOT NULL, `description` varchar(200) NOT NULL, `callback_url` varchar(200) NOT NULL, `date_publish` datetime(6) NOT NULL, `index` integer NOT NULL); args=None
2018-06-02 15:27:45,514 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,516 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,519 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,522 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,525 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,528 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_links'; args=['blog_links']
2018-06-02 15:27:45,529 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_tag` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(30) NOT NULL); (params None)
2018-06-02 15:27:45,653 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.124) CREATE TABLE `blog_tag` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(30) NOT NULL); args=None
2018-06-02 15:27:45,656 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_tag'; args=['blog_tag']
2018-06-02 15:27:45,658 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_tag'; args=['blog_tag']
2018-06-02 15:27:45,666 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article` ADD COLUMN `category_id` integer NULL; (params [])
2018-06-02 15:27:45,928 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.261) ALTER TABLE `blog_article` ADD COLUMN `category_id` integer NULL; args=[]
2018-06-02 15:27:45,931 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:45,949 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `blog_article_tag` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `article_id` integer NOT NULL, `tag_id` integer NOT NULL); (params None)
2018-06-02 15:27:46,097 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.148) CREATE TABLE `blog_article_tag` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `article_id` integer NOT NULL, `tag_id` integer NOT NULL); args=None
2018-06-02 15:27:46,099 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article_tag'; args=['blog_article_tag']
2018-06-02 15:27:46,101 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article_tag'; args=['blog_article_tag']
2018-06-02 15:27:46,103 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article_tag'; args=['blog_article_tag']
2018-06-02 15:27:46,116 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article` ADD COLUMN `user_id` integer NOT NULL; (params [])
2018-06-02 15:27:46,387 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.271) ALTER TABLE `blog_article` ADD COLUMN `user_id` integer NOT NULL; args=[]
2018-06-02 15:27:46,389 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'blog_article'; args=['blog_article']
2018-06-02 15:27:46,390 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_groups` ADD CONSTRAINT `blog_user_groups_user_id_4e1acb48_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); (params ())
2018-06-02 15:27:46,862 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.471) ALTER TABLE `blog_user_groups` ADD CONSTRAINT `blog_user_groups_user_id_4e1acb48_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); args=()
2018-06-02 15:27:46,863 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_groups` ADD CONSTRAINT `blog_user_groups_group_id_29990e74_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params ())
2018-06-02 15:27:47,283 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.418) ALTER TABLE `blog_user_groups` ADD CONSTRAINT `blog_user_groups_group_id_29990e74_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); args=()
2018-06-02 15:27:47,284 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_groups` ADD CONSTRAINT blog_user_groups_user_id_group_id_9046f296_uniq UNIQUE (`user_id`, `group_id`); (params ())
2018-06-02 15:27:47,435 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.146) ALTER TABLE `blog_user_groups` ADD CONSTRAINT blog_user_groups_user_id_group_id_9046f296_uniq UNIQUE (`user_id`, `group_id`); args=()
2018-06-02 15:27:47,436 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT `blog_user_user_permissions_user_id_379a1502_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); (params ())
2018-06-02 15:27:47,822 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.384) ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT `blog_user_user_permissions_user_id_379a1502_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); args=()
2018-06-02 15:27:47,823 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT `blog_user_user_permi_permission_id_95ca6010_fk_auth_perm` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params ())
2018-06-02 15:27:48,203 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.376) ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT `blog_user_user_permi_permission_id_95ca6010_fk_auth_perm` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); args=()
2018-06-02 15:27:48,204 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT blog_user_user_permissions_user_id_permission_id_1d3c1311_uniq UNIQUE (`user_id`, `permission_id`); (params ())
2018-06-02 15:27:48,390 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.186) ALTER TABLE `blog_user_user_permissions` ADD CONSTRAINT blog_user_user_permissions_user_id_permission_id_1d3c1311_uniq UNIQUE (`user_id`, `permission_id`); args=()
2018-06-02 15:27:48,391 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_article_id_3d58bca6_fk_blog_article_id` FOREIGN KEY (`article_id`) REFERENCES `blog_article` (`id`); (params ())
2018-06-02 15:27:48,762 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.366) ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_article_id_3d58bca6_fk_blog_article_id` FOREIGN KEY (`article_id`) REFERENCES `blog_article` (`id`); args=()
2018-06-02 15:27:48,762 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_pid_id_2a2b4cc4_fk_blog_comment_id` FOREIGN KEY (`pid_id`) REFERENCES `blog_comment` (`id`); (params ())
2018-06-02 15:27:49,617 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.854) ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_pid_id_2a2b4cc4_fk_blog_comment_id` FOREIGN KEY (`pid_id`) REFERENCES `blog_comment` (`id`); args=()
2018-06-02 15:27:49,618 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_user_id_59a54155_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); (params ())
2018-06-02 15:27:49,989 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.370) ALTER TABLE `blog_comment` ADD CONSTRAINT `blog_comment_user_id_59a54155_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); args=()
2018-06-02 15:27:49,991 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article` ADD CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`); (params ())
2018-06-02 15:27:50,393 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.400) ALTER TABLE `blog_article` ADD CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`); args=()
2018-06-02 15:27:50,394 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article_tag` ADD CONSTRAINT `blog_article_tag_article_id_8db2395e_fk_blog_article_id` FOREIGN KEY (`article_id`) REFERENCES `blog_article` (`id`); (params ())
2018-06-02 15:27:50,845 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.449) ALTER TABLE `blog_article_tag` ADD CONSTRAINT `blog_article_tag_article_id_8db2395e_fk_blog_article_id` FOREIGN KEY (`article_id`) REFERENCES `blog_article` (`id`); args=()
2018-06-02 15:27:50,845 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article_tag` ADD CONSTRAINT `blog_article_tag_tag_id_f2afe66b_fk_blog_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `blog_tag` (`id`); (params ())
2018-06-02 15:27:51,362 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.517) ALTER TABLE `blog_article_tag` ADD CONSTRAINT `blog_article_tag_tag_id_f2afe66b_fk_blog_tag_id` FOREIGN KEY (`tag_id`) REFERENCES `blog_tag` (`id`); args=()
2018-06-02 15:27:51,363 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article_tag` ADD CONSTRAINT blog_article_tag_article_id_tag_id_818e752b_uniq UNIQUE (`article_id`, `tag_id`); (params ())
2018-06-02 15:27:51,587 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.223) ALTER TABLE `blog_article_tag` ADD CONSTRAINT blog_article_tag_article_id_tag_id_818e752b_uniq UNIQUE (`article_id`, `tag_id`); args=()
2018-06-02 15:27:51,587 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `blog_article` ADD CONSTRAINT `blog_article_user_id_5beb0cc1_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); (params ())
2018-06-02 15:27:52,082 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.494) ALTER TABLE `blog_article` ADD CONSTRAINT `blog_article_user_id_5beb0cc1_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); args=()
2018-06-02 15:27:52,087 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:27:52,088 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('blog', '0001_initial', '2018-06-02 07:27:52.088231'); args=['blog', '0001_initial', '2018-06-02 07:27:52.088231']
2018-06-02 15:27:52,187 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime(6) NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
2018-06-02 15:27:52,375 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.187) CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime(6) NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); args=None
2018-06-02 15:27:52,410 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.033) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,413 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,415 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,418 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,424 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,426 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,428 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,430 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'django_admin_log'; args=['django_admin_log']
2018-06-02 15:27:52,430 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params ())
2018-06-02 15:27:53,252 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.821) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); args=()
2018-06-02 15:27:53,252 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); (params ())
2018-06-02 15:27:53,862 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.609) ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_c564eba6_fk_blog_user_id` FOREIGN KEY (`user_id`) REFERENCES `blog_user` (`id`); args=()
2018-06-02 15:27:53,866 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2018-06-02 15:27:53,867 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0001_initial', '2018-06-02 07:27:53.866701'); args=['admin', '0001_initial', '2018-06-02 07:27:53.866701']
2018-06-02 15:27:53,914 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2018-06-02 15:27:53,915 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0002_logentry_remove_auto_add', '2018-06-02 07:27:53.915369'); args=['admin', '0002_logentry_remove_auto_add', '2018-06-02 07:27:53.915369']
2018-06-02 15:27:53,944 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL); (params None)
2018-06-02 15:27:54,152 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.207) CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL); args=None
2018-06-02 15:27:54,157 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT engine FROM information_schema.tables WHERE table_name = 'django_session'; args=['django_session']
2018-06-02 15:27:54,159 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_session'; args=['django_session']
2018-06-02 15:27:54,162 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT engine FROM information_schema.tables WHERE table_name = 'django_session'; args=['django_session']
2018-06-02 15:27:54,162 [MainThread:11404] [django.db.backends.schema:124] [schema:execute] [DEBUG]- CREATE INDEX `django_session_expire_date_a5c62663` ON `django_session` (`expire_date`); (params ())
2018-06-02 15:27:54,309 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.146) CREATE INDEX `django_session_expire_date_a5c62663` ON `django_session` (`expire_date`); args=()
2018-06-02 15:27:54,314 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SHOW FULL TABLES; args=None
2018-06-02 15:27:54,316 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('sessions', '0001_initial', '2018-06-02 07:27:54.315759'); args=['sessions', '0001_initial', '2018-06-02 07:27:54.315759']
2018-06-02 15:27:54,358 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:27:54,360 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-02 15:27:54,377 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'admin' AND `django_content_type`.`model` = 'logentry'); args=('admin', 'logentry')
2018-06-02 15:27:54,380 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'admin' AND `django_content_type`.`model` = 'logentry'); args=('admin', 'logentry')
2018-06-02 15:27:54,382 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('admin', 'logentry'); args=['admin', 'logentry']
2018-06-02 15:27:54,411 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2018-06-02 15:27:54,413 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add log entry', 1, 'add_logentry'), ('Can change log entry', 1, 'change_logentry'), ('Can delete log entry', 1, 'delete_logentry'); args=('Can add log entry', 1, 'add_logentry', 'Can change log entry', 1, 'change_logentry', 'Can delete log entry', 1, 'delete_logentry')
2018-06-02 15:27:54,441 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2018-06-02 15:27:54,443 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'permission'); args=('auth', 'permission')
2018-06-02 15:27:54,446 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'permission'); args=('auth', 'permission')
2018-06-02 15:27:54,447 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'permission'); args=['auth', 'permission']
2018-06-02 15:27:54,476 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'group'); args=('auth', 'group')
2018-06-02 15:27:54,477 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'group'); args=('auth', 'group')
2018-06-02 15:27:54,478 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('auth', 'group'); args=['auth', 'group']
2018-06-02 15:27:54,523 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3)
2018-06-02 15:27:54,608 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.084) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add permission', 2, 'add_permission'), ('Can change permission', 2, 'change_permission'), ('Can delete permission', 2, 'delete_permission'), ('Can add group', 3, 'add_group'), ('Can change group', 3, 'change_group'), ('Can delete group', 3, 'delete_group'); args=('Can add permission', 2, 'add_permission', 'Can change permission', 2, 'change_permission', 'Can delete permission', 2, 'delete_permission', 'Can add group', 3, 'add_group', 'Can change group', 3, 'change_group', 'Can delete group', 3, 'delete_group')
2018-06-02 15:27:54,632 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2018-06-02 15:27:54,635 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'contenttypes' AND `django_content_type`.`model` = 'contenttype'); args=('contenttypes', 'contenttype')
2018-06-02 15:27:54,639 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'contenttypes' AND `django_content_type`.`model` = 'contenttype'); args=('contenttypes', 'contenttype')
2018-06-02 15:27:54,642 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('contenttypes', 'contenttype'); args=['contenttypes', 'contenttype']
2018-06-02 15:27:54,667 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(4,)
2018-06-02 15:27:54,669 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add content type', 4, 'add_contenttype'), ('Can change content type', 4, 'change_contenttype'), ('Can delete content type', 4, 'delete_contenttype'); args=('Can add content type', 4, 'add_contenttype', 'Can change content type', 4, 'change_contenttype', 'Can delete content type', 4, 'delete_contenttype')
2018-06-02 15:27:54,704 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2018-06-02 15:27:54,708 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'sessions' AND `django_content_type`.`model` = 'session'); args=('sessions', 'session')
2018-06-02 15:27:54,709 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'sessions' AND `django_content_type`.`model` = 'session'); args=('sessions', 'session')
2018-06-02 15:27:54,711 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('sessions', 'session'); args=['sessions', 'session']
2018-06-02 15:27:54,737 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2018-06-02 15:27:54,739 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add session', 5, 'add_session'), ('Can change session', 5, 'change_session'), ('Can delete session', 5, 'delete_session'); args=('Can add session', 5, 'add_session', 'Can change session', 5, 'change_session', 'Can delete session', 5, 'delete_session')
2018-06-02 15:27:54,759 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2018-06-02 15:27:54,760 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'user'); args=('blog', 'user')
2018-06-02 15:27:54,762 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'user'); args=('blog', 'user')
2018-06-02 15:27:54,764 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'user'); args=['blog', 'user']
2018-06-02 15:27:54,794 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'ad'); args=('blog', 'ad')
2018-06-02 15:27:54,796 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'ad'); args=('blog', 'ad')
2018-06-02 15:27:54,798 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'ad'); args=['blog', 'ad']
2018-06-02 15:27:54,828 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'article'); args=('blog', 'article')
2018-06-02 15:27:54,829 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'article'); args=('blog', 'article')
2018-06-02 15:27:54,831 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'article'); args=['blog', 'article']
2018-06-02 15:27:54,913 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'category'); args=('blog', 'category')
2018-06-02 15:27:54,915 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'category'); args=('blog', 'category')
2018-06-02 15:27:54,916 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'category'); args=['blog', 'category']
2018-06-02 15:27:54,947 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'comment'); args=('blog', 'comment')
2018-06-02 15:27:54,949 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'comment'); args=('blog', 'comment')
2018-06-02 15:27:54,951 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'comment'); args=['blog', 'comment']
2018-06-02 15:27:54,982 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'links'); args=('blog', 'links')
2018-06-02 15:27:54,985 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'links'); args=('blog', 'links')
2018-06-02 15:27:54,988 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'links'); args=['blog', 'links']
2018-06-02 15:27:55,020 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'tag'); args=('blog', 'tag')
2018-06-02 15:27:55,022 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'tag'); args=('blog', 'tag')
2018-06-02 15:27:55,024 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('blog', 'tag'); args=['blog', 'tag']
2018-06-02 15:27:55,052 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6, 7, 8, 9, 10, 11, 12) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6, 7, 8, 9, 10, 11, 12)
2018-06-02 15:27:55,055 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add 用户', 6, 'add_user'), ('Can change 用户', 6, 'change_user'), ('Can delete 用户', 6, 'delete_user'), ('Can add 广告', 7, 'add_ad'), ('Can change 广告', 7, 'change_ad'), ('Can delete 广告', 7, 'delete_ad'), ('Can add 文章', 8, 'add_article'), ('Can change 文章', 8, 'change_article'), ('Can delete 文章', 8, 'delete_article'), ('Can add 分类', 9, 'add_category'), ('Can change 分类', 9, 'change_category'), ('Can delete 分类', 9, 'delete_category'), ('Can add 评论', 10, 'add_comment'), ('Can change 评论', 10, 'change_comment'), ('Can delete 评论', 10, 'delete_comment'), ('Can add 友情链接', 11, 'add_links'), ('Can change 友情链接', 11, 'change_links'), ('Can delete 友情链接', 11, 'delete_links'), ('Can add 标签', 12, 'add_tag'), ('Can change 标签', 12, 'change_tag'), ('Can delete 标签', 12, 'delete_tag'); args=('Can add 用户', 6, 'add_user', 'Can change 用户', 6, 'change_user', 'Can delete 用户', 6, 'delete_user', 'Can add 广告', 7, 'add_ad', 'Can change 广告', 7, 'change_ad', 'Can delete 广告', 7, 'delete_ad', 'Can add 文章', 8, 'add_article', 'Can change 文章', 8, 'change_article', 'Can delete 文章', 8, 'delete_article', 'Can add 分类', 9, 'add_category', 'Can change 分类', 9, 'change_category', 'Can delete 分类', 9, 'delete_category', 'Can add 评论', 10, 'add_comment', 'Can change 评论', 10, 'change_comment', 'Can delete 评论', 10, 'delete_comment', 'Can add 友情链接', 11, 'add_links', 'Can change 友情链接', 11, 'change_links', 'Can delete 友情链接', 11, 'delete_links', 'Can add 标签', 12, 'add_tag', 'Can change 标签', 12, 'change_tag', 'Can delete 标签', 12, 'delete_tag')
2018-06-02 15:27:55,148 [MainThread:11404] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'blog'; args=('blog',)
2018-06-02 15:28:26,866 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-02 15:28:26,867 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:28:26,869 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-02 15:28:26,942 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-02 15:28:26,947 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-02 15:28:26,955 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-02 15:28:38,991 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`username` = 'admin'; args=('admin',)
2018-06-02 15:28:55,189 [MainThread:11492] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) INSERT INTO `blog_user` (`password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`, `avatar`, `qq`, `mobile`, `url`) VALUES ('pbkdf2_sha256$100000$4gdnmGWRRojI$hYie6SvXpo2YXljQwIhZPVgjA1JF7+w6t/ncb/8DLxw=', NULL, 1, 'admin', '', '', 'admin@admin.com', 1, 1, '2018-06-02 07:28:55.038515', 'avatar/default.png', NULL, NULL, NULL); args=['pbkdf2_sha256$100000$4gdnmGWRRojI$hYie6SvXpo2YXljQwIhZPVgjA1JF7+w6t/ncb/8DLxw=', None, True, 'admin', '', '', 'admin@admin.com', True, True, '2018-06-02 07:28:55.038515', 'avatar/default.png', None, None, None]
2018-06-03 09:41:02,139 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:02,231 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:02,232 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:41:02,320 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:02,827 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.506) SHOW FULL TABLES; args=None
2018-06-03 09:41:02,838 [Dummy-1:13120] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-03 09:41:09,864 [Thread-2:1464] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
2018-06-03 09:41:10,193 [Thread-3:16268] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06DEAB28>>, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x068DDA70>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06E28E70>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x068DD9F0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'view': <django.contrib.auth.views.LoginView object at 0x06E04130>, 'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': False, 'available_apps': [], 'title': 'Log in', 'app_path': '/admin/login/?next=/admin/', 'username': '', 'next': '/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x06E043F0>, 'site_name': '127.0.0.1:8000', 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2018-06-03 09:41:10,241 [Thread-3:16268] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x06DEAB28>>, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x068DDA70>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06E28E70>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x068DD9F0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'view': <django.contrib.auth.views.LoginView object at 0x06E04130>, 'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': False, 'available_apps': [], 'title': 'Log in', 'app_path': '/admin/login/?next=/admin/', 'username': '', 'next': '/admin/', 'site': <django.contrib.sites.requests.RequestSite object at 0x06E043F0>, 'site_name': '127.0.0.1:8000', 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2018-06-03 09:41:10,257 [Thread-3:16268] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1855
2018-06-03 09:41:10,276 [Thread-4:7440] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css HTTP/1.1" 304 0
2018-06-03 09:41:10,333 [Thread-5:5144] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/login.css HTTP/1.1" 304 0
2018-06-03 09:41:10,334 [Thread-6:11080] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
2018-06-03 09:41:10,358 [Thread-7:17840] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/nav-bg.gif HTTP/1.1" 404 1684
2018-06-03 09:41:10,432 [Thread-8:10332] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\env\env_mysite\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "F:\env\env_mysite\lib\site-packages\django\urls\resolvers.py", line 523, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLPattern '^$' [name='index']>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2018-06-03 09:41:10,472 [Thread-8:10332] [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2094
2018-06-03 09:41:13,267 [Thread-9:12004] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/nav-bg-reverse.gif HTTP/1.1" 404 1708
2018-06-03 09:41:13,397 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:13,398 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:13,399 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:41:13,413 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:13,418 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`username` = 'admin'; args=('admin',)
2018-06-03 09:41:13,537 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4' LIMIT 1; args=('jhtiwy08eo3fpsuj1481lcoioaxxhyg4',)
2018-06-03 09:41:13,540 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('jhtiwy08eo3fpsuj1481lcoioaxxhyg4', 'YzkwNDBkNzQzNDNiMzcxYzliNjI2M2Q2ZTI0YmRmMzNkMzQ3YzFlNTp7fQ==', '2018-06-17 01:41:13.538508'); args=('jhtiwy08eo3fpsuj1481lcoioaxxhyg4', 'YzkwNDBkNzQzNDNiMzcxYzliNjI2M2Q2ZTI0YmRmMzNkMzQ3YzFlNTp7fQ==', '2018-06-17 01:41:13.538508')
2018-06-03 09:41:13,565 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) UPDATE `blog_user` SET `last_login` = '2018-06-03 01:41:13.563073' WHERE `blog_user`.`id` = 1; args=('2018-06-03 01:41:13.563073', 1)
2018-06-03 09:41:13,582 [Thread-10:18948] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) UPDATE `django_session` SET `session_data` = 'MWYxYTU1NTU1ODU2NzJkMmFjZTZiYjQxZGE1ZDZkYmRjYmM3ZGQ2ZTp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiJlZDgzZTM1MWY3NzVjNjYzNGNmZDdiY2ExYmM3ZWMxYjIxYjU4MTRhIn0=', `expire_date` = '2018-06-17 01:41:13.580619' WHERE `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'; args=('MWYxYTU1NTU1ODU2NzJkMmFjZTZiYjQxZGE1ZDZkYmRjYmM3ZGQ2ZTp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiJlZDgzZTM1MWY3NzVjNjYzNGNmZDdiY2ExYmM3ZWMxYjIxYjU4MTRhIn0=', '2018-06-17 01:41:13.580619', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:13,625 [Thread-10:18948] [django.server:124] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2018-06-03 09:41:13,631 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:13,631 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:13,632 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:41:13,634 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:13,663 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.029) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:41:13.628748' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:41:13.628748', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:13,667 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:41:13,685 [Thread-11:8508] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069AAB28>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06E3CBF0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06E28CB0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}]}, {'name': 'Blog', 'app_label': 'blog', 'app_url': '/admin/blog/', 'has_module_perms': True, 'models': [{'name': '分类', 'object_name': 'Category', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/category/', 'add_url': '/admin/blog/category/add/'}, {'name': '友情链接', 'object_name': 'Links', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/links/', 'add_url': '/admin/blog/links/add/'}, {'name': '广告', 'object_name': 'Ad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/ad/', 'add_url': '/admin/blog/ad/add/'}, {'name': '文章', 'object_name': 'Article', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/article/', 'add_url': '/admin/blog/article/add/'}, {'name': '标签', 'object_name': 'Tag', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/tag/', 'add_url': '/admin/blog/tag/add/'}, {'name': '用户', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/user/', 'add_url': '/admin/blog/user/add/'}, {'name': '评论', 'object_name': 'Comment', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/comment/', 'add_url': '/admin/blog/comment/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}]}, {'name': 'Blog', 'app_label': 'blog', 'app_url': '/admin/blog/', 'has_module_perms': True, 'models': [{'name': '分类', 'object_name': 'Category', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/category/', 'add_url': '/admin/blog/category/add/'}, {'name': '友情链接', 'object_name': 'Links', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/links/', 'add_url': '/admin/blog/links/add/'}, {'name': '广告', 'object_name': 'Ad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/ad/', 'add_url': '/admin/blog/ad/add/'}, {'name': '文章', 'object_name': 'Article', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/article/', 'add_url': '/admin/blog/article/add/'}, {'name': '标签', 'object_name': 'Tag', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/tag/', 'add_url': '/admin/blog/tag/add/'}, {'name': '用户', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/user/', 'add_url': '/admin/blog/user/add/'}, {'name': '评论', 'object_name': 'Comment', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/comment/', 'add_url': '/admin/blog/comment/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2018-06-03 09:41:13,689 [Thread-11:8508] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069AAB28>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x06E3CBF0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x06E28CB0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'SITE_NAME': '鸟嘌呤的个人博客', 'SITE_DESC': '专注Python开发，欢迎和大家交流'}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}]}, {'name': 'Blog', 'app_label': 'blog', 'app_url': '/admin/blog/', 'has_module_perms': True, 'models': [{'name': '分类', 'object_name': 'Category', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/category/', 'add_url': '/admin/blog/category/add/'}, {'name': '友情链接', 'object_name': 'Links', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/links/', 'add_url': '/admin/blog/links/add/'}, {'name': '广告', 'object_name': 'Ad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/ad/', 'add_url': '/admin/blog/ad/add/'}, {'name': '文章', 'object_name': 'Article', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/article/', 'add_url': '/admin/blog/article/add/'}, {'name': '标签', 'object_name': 'Tag', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/tag/', 'add_url': '/admin/blog/tag/add/'}, {'name': '用户', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/user/', 'add_url': '/admin/blog/user/add/'}, {'name': '评论', 'object_name': 'Comment', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/comment/', 'add_url': '/admin/blog/comment/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}]}, {'name': 'Blog', 'app_label': 'blog', 'app_url': '/admin/blog/', 'has_module_perms': True, 'models': [{'name': '分类', 'object_name': 'Category', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/category/', 'add_url': '/admin/blog/category/add/'}, {'name': '友情链接', 'object_name': 'Links', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/links/', 'add_url': '/admin/blog/links/add/'}, {'name': '广告', 'object_name': 'Ad', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/ad/', 'add_url': '/admin/blog/ad/add/'}, {'name': '文章', 'object_name': 'Article', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/article/', 'add_url': '/admin/blog/article/add/'}, {'name': '标签', 'object_name': 'Tag', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/tag/', 'add_url': '/admin/blog/tag/add/'}, {'name': '用户', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/user/', 'add_url': '/admin/blog/user/add/'}, {'name': '评论', 'object_name': 'Comment', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/blog/comment/', 'add_url': '/admin/blog/comment/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2018-06-03 09:41:13,704 [Thread-11:8508] [django.db.backends:111] [utils:execute] [DEBUG]- (0.008) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `blog_user` ON (`django_admin_log`.`user_id` = `blog_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2018-06-03 09:41:13,705 [Thread-11:8508] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 5557
2018-06-03 09:41:13,723 [Thread-12:16692] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
2018-06-03 09:41:13,743 [Thread-14:3932] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/icon_changelink.gif HTTP/1.1" 404 1711
2018-06-03 09:41:13,745 [Thread-13:17944] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/nav-bg.gif HTTP/1.1" 404 1684
2018-06-03 09:41:13,752 [Thread-15:11552] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/icon_addlink.gif HTTP/1.1" 404 1702
2018-06-03 09:41:13,753 [Thread-16:4988] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/default-bg.gif HTTP/1.1" 404 1696
2018-06-03 09:41:17,236 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:17,236 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:17,237 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-06-03 09:41:17,258 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:17,264 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:41:17.231588' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:41:17.231588', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:17,270 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:41:17,280 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT COUNT(*) AS `__count` FROM `blog_article`; args=()
2018-06-03 09:41:17,282 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT COUNT(*) AS `__count` FROM `blog_article`; args=()
2018-06-03 09:41:17,286 [Thread-17:5660] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `blog_article`.`id`, `blog_article`.`title`, `blog_article`.`desc`, `blog_article`.`content`, `blog_article`.`click_count`, `blog_article`.`is_recommend`, `blog_article`.`date_publish`, `blog_article`.`user_id`, `blog_article`.`category_id` FROM `blog_article` ORDER BY `blog_article`.`date_publish` DESC, `blog_article`.`id` DESC; args=()
2018-06-03 09:41:17,304 [Thread-17:5660] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in None
2018-06-03 09:41:17,309 [Thread-17:5660] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "F:\env\env_mysite\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in [{'True': True, 'False': False, 'None': None, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x069AAA98>>}]
2018-06-03 09:41:17,315 [Thread-17:5660] [django.template:878] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\env\env_mysite\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in None
2018-06-03 09:41:17,322 [Thread-17:5660] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/blog/article/ HTTP/1.1" 200 3237
2018-06-03 09:41:17,342 [Thread-18:16172] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
2018-06-03 09:41:17,344 [Thread-20:17616] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
2018-06-03 09:41:17,345 [Thread-22:10488] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 304 0
2018-06-03 09:41:17,345 [Thread-19:6976] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
2018-06-03 09:41:17,348 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:17,353 [Thread-23:6072] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
2018-06-03 09:41:17,384 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:17,387 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-06-03 09:41:17,391 [Thread-24:9576] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
2018-06-03 09:41:17,394 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:17,395 [Thread-25:1052] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
2018-06-03 09:41:17,399 [Thread-26:2148] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
2018-06-03 09:41:17,400 [Thread-27:6656] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 304 0
2018-06-03 09:41:17,403 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:41:17.340378' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:41:17.340378', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:17,414 [Thread-21:808] [django.db.backends:111] [utils:execute] [DEBUG]- (0.007) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:41:17,419 [Thread-21:808] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-03 09:41:17,458 [Thread-28:5292] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/tooltag-add.png HTTP/1.1" 404 1699
2018-06-03 09:41:17,466 [Thread-29:8480] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/nav-bg-reverse.gif HTTP/1.1" 404 1708
2018-06-03 09:41:22,335 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:22,336 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:22,337 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:41:22,340 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:22,341 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:41:22.332030' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:41:22.332030', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:22,349 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:41:22,353 [Thread-30:4256] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'article'); args=('blog', 'article')
2018-06-03 09:41:22,461 [Thread-30:4256] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/blog/article/add/ HTTP/1.1" 200 5012
2018-06-03 09:41:22,475 [Thread-31:14124] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 304 0
2018-06-03 09:41:22,477 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:41:22,480 [Thread-33:10484] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
2018-06-03 09:41:22,480 [Thread-34:13216] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
2018-06-03 09:41:22,484 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:22,487 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:41:22,490 [Thread-35:17372] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
2018-06-03 09:41:22,493 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:41:22,500 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:41:22.471842' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:41:22.471842', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:41:22,502 [Thread-32:16364] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:41:22,508 [Thread-32:16364] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-03 09:41:22,550 [Thread-36:18356] [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/admin/img/default-bg.gif HTTP/1.1" 404 1696
2018-06-03 09:57:18,152 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:57:18,153 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:18,154 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:57:18,241 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:18,244 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-03 09:57:18,251 [Dummy-1:14440] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-03 09:57:27,081 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:57:27,082 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:27,082 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:57:27,167 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:27,170 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.003) SHOW FULL TABLES; args=None
2018-06-03 09:57:27,176 [Dummy-1:7984] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-03 09:57:39,749 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:57:39,750 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:39,753 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 09:57:39,759 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:39,760 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:57:39.746989' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:57:39.746989', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:57:39,764 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:57:39,792 [Thread-2:15260] [django.db.backends:111] [utils:execute] [DEBUG]- (0.006) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'article'); args=('blog', 'article')
2018-06-03 09:57:39,948 [Thread-2:15260] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/blog/article/add/ HTTP/1.1" 200 6136
2018-06-03 09:57:39,963 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 09:57:39,964 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:39,965 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-06-03 09:57:39,977 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 09:57:39,978 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 01:57:39.961120' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 01:57:39.961120', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 09:57:39,981 [Thread-3:17728] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 09:57:39,985 [Thread-3:17728] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-03 09:57:40,010 [Thread-4:16120] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/admin/js/collapse.js HTTP/1.1" 200 1151
2018-06-03 10:46:39,684 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 10:46:39,685 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:39,686 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 10:46:39,790 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:39,795 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SHOW FULL TABLES; args=None
2018-06-03 10:46:39,803 [Dummy-1:18424] [django.db.backends:111] [utils:execute] [DEBUG]- (0.005) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-06-03 10:46:47,352 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 10:46:47,352 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:47,353 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-06-03 10:46:47,360 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:47,362 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 02:46:47.348738' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 02:46:47.348738', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 10:46:47,368 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.002) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 10:46:47,401 [Thread-2:17108] [django.db.backends:111] [utils:execute] [DEBUG]- (0.004) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'blog' AND `django_content_type`.`model` = 'article'); args=('blog', 'article')
2018-06-03 10:46:47,458 [Thread-2:17108] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/blog/article/add/ HTTP/1.1" 200 6406
2018-06-03 10:46:47,473 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 10:46:47,474 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:47,479 [Thread-6:5740] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/js/kindeditor-4.1.10/config.js HTTP/1.1" 200 251
2018-06-03 10:46:47,493 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-06-03 10:46:47,498 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 10:46:47,499 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2018-06-03 02:46:47.466526' AND `django_session`.`session_key` = 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4'); args=('2018-06-03 02:46:47.466526', 'jhtiwy08eo3fpsuj1481lcoioaxxhyg4')
2018-06-03 10:46:47,500 [Thread-3:12820] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT `blog_user`.`id`, `blog_user`.`password`, `blog_user`.`last_login`, `blog_user`.`is_superuser`, `blog_user`.`username`, `blog_user`.`first_name`, `blog_user`.`last_name`, `blog_user`.`email`, `blog_user`.`is_staff`, `blog_user`.`is_active`, `blog_user`.`date_joined`, `blog_user`.`avatar`, `blog_user`.`qq`, `blog_user`.`mobile`, `blog_user`.`url` FROM `blog_user` WHERE `blog_user`.`id` = 1; args=(1,)
2018-06-03 10:46:47,504 [Thread-3:12820] [django.server:124] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-03 10:46:47,596 [Thread-5:13816] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/js/kindeditor-4.1.10/lang/zh_CN.js HTTP/1.1" 200 8488
2018-06-03 10:46:47,606 [Thread-4:9580] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/js/kindeditor-4.1.10/kindeditor-min.js HTTP/1.1" 200 94446
2018-06-03 10:46:47,674 [Thread-7:9488] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/js/kindeditor-4.1.10/themes/default/default.css HTTP/1.1" 200 21967
2018-06-03 10:46:47,747 [Thread-8:16200] [django.server:124] [basehttp:log_message] [INFO]- "GET /static/js/kindeditor-4.1.10/themes/default/default.png HTTP/1.1" 200 8299
2018-06-03 11:10:55,261 [Dummy-1:18576] [django.db.backends:111] [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-06-03 11:10:55,262 [Dummy-1:18576] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2018-06-03 11:10:55,262 [Dummy-1:18576] [django.db.backends:111] [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
